### ISSUE TITLE
Plugin com.vertispan.j2cl:j2cl-maven-plugin:0.15-SNAPSHOT or one of its dependencies could not be resolved

### ISSUE THREAD

**Issue by rhusar** [treblereel/quake2-gwt-port#12]
[INFO] ------------------< org.treblereel.gwt.quake2:client >------------------
[INFO] Building client 1.0-SNAPSHOT                                       [5/6]
[INFO] --------------------------------[ war ]---------------------------------
Downloading from jboss-public-repository-group: https://repository.jboss.org/nexus/content/groups/public-jboss/com/vertispan/j2cl/j2cl-maven-plugin/0.15-SNAPSHOT/maven-metadata.xml
Downloading from jboss-public-repository-group: https://repository.jboss.org/nexus/content/groups/public-jboss/com/vertispan/j2cl/j2cl-maven-plugin/0.15-SNAPSHOT/j2cl-maven-plugin-0.15-SNAPSHOT.pom
[WARNING] The POM for com.vertispan.j2cl:j2cl-maven-plugin:jar:0.15-SNAPSHOT is missing, no dependency information available
Downloading from jboss-public-repository-group: https://repository.jboss.org/nexus/content/groups/public-jboss/com/vertispan/j2cl/j2cl-maven-plugin/0.15-SNAPSHOT/j2cl-maven-plugin-0.15-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for parent 1.0-SNAPSHOT:
[INFO]
[INFO] parent ............................................. SUCCESS [  0.267 s]
[INFO] emul ............................................... SUCCESS [  0.007 s]
[INFO] io ................................................. SUCCESS [ 10.056 s]
[INFO] shared ............................................. SUCCESS [  6.030 s]
[INFO] client ............................................. FAILURE [  0.564 s]
[INFO] server ............................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  20.465 s
[INFO] Finished at: 2020-06-28T22:48:11+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin com.vertispan.j2cl:j2cl-maven-plugin:0.15-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact com.vertispan.j2cl:j2cl-maven-plugin:jar:0.15-SNAPSHOT in jboss-public-repository-group (https://repository.jboss.org/nexus/content/groups/public-jboss) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException

**Comment by treblereel** [comment]
@rhusar sorry, i missed it, let fix this ...
